#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Verifica se o commit atual é um commit de release
commit_msg=$(git log -1 --pretty=%B)
if echo "$commit_msg" | grep -q "^chore(release):"; then
  # Se for um commit de release, apenas faz push
  git push --follow-tags origin main
else
  # Se não for um commit de release, gera uma nova versão
  npx standard-version
  git push --follow-tags origin main
fi